"""empty message

Revision ID: 0f9d868e0e68
Revises: 617b8ed00faf
Create Date: 2024-01-24 00:19:59.560965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9d868e0e68'
down_revision = '617b8ed00faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('noofcopies',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('storage',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sound',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('issued_book', schema=None) as batch_op:
        batch_op.alter_column('issue_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('return_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('purchased_book', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchased_book', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('issued_book', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('return_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('return_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('issue_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('sound',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('storage',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('noofcopies',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
