"""empty message

Revision ID: 3de3dc4a8bb9
Revises: 0f9d868e0e68
Create Date: 2024-01-24 00:29:46.248802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de3dc4a8bb9'
down_revision = '0f9d868e0e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ratings_user_id'), ['user_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ratings_user_id'), type_='unique')

    # ### end Alembic commands ###
