"""empty message

Revision ID: 617b8ed00faf
Revises: c3223195c11a
Create Date: 2024-01-24 00:01:03.920141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617b8ed00faf'
down_revision = 'c3223195c11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payment_details_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_details_user_id'), type_='unique')

    # ### end Alembic commands ###
